### ISSUE TITLE
Merge with "eslint-plugin-ember-cleanup"

### ISSUE THREAD

**Issue by Turbo87** [zipscene/eslint-plugin-ember#3]
It seems like wasted effort to have two separate ESLint plugins for Ember.js. It would be awesome if this project would merge with [eslint-plugin-ember-cleanup](https://github.com/onechiporenko/eslint-plugin-ember-cleanup) and offer all of the rules in the "eslint-plugin-ember" package

**Comment by rjhilgefort** [comment]
It would be great to merge. I'm not sure I currently have the time to put in work on the merge. @Turbo87 would you be willing to champion that effort? If so, I'd be happy to review a PR. I believe that this repo has the desired Eslint namespace, and should therefore be the namespace we merge onto. You may want to discuss that with the owner of the other repo in the issue you raised there as well onechiporenko/eslint-plugin-ember-cleanup#1.

If you were to spend time on the merge, I would take the time to clean this repo up so we have a central place to build up a common rule set for the community.

**Comment by BrianSipple** [comment]
I'd be interested in helping out with this as well, as I think it would be great to have a [community rule set to compliment `ember-cli-eslint`](https://github.com/ember-cli/ember-cli-eslint/pull/53)(even just living alongside it).

My main question revolves around what our approach would be. @Turbo87, @rjhilgefort, and @onechiporenko, it would be great to get a discussion started here about what rules we want to use, general project architecture, etc.

**Comment by rjhilgefort** [comment]
@BrianSipple Sounds good to me. First thing is addressing the two repos. Still need some buy in from @Turbo87 and @onechiporenko.

**Comment by scottkidder** [comment]
Where is this at? I stumbled across https://github.com/onechiporenko/eslint-plugin-ember-cleanup and some of the rules seem very useful.

**Comment by Turbo87** [comment]
@scottkidder this project is the official "custom ESLint rules for Ember.js" project now. it would be awesome if someone would import the most useful rules from https://github.com/onechiporenko/eslint-plugin-ember-cleanup into this project.

**Comment by rawsp33d** [comment]
It seems like people were just politely allowing the author of the other project to give his input.  But I think a year and a half ought to be sufficient.

**Comment by Turbo87** [comment]
whooooops, sorry, I just looked at the project name. what I meant was actually https://github.com/ember-cli/eslint-plugin-ember being the official project.

**Comment by rawsp33d** [comment]
That makes a lot more sense, considering we haven't touched this in three years 😉.
